{ pkgs }: {
	deps = [
		pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.gnat
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.libgccjit
  pkgs.main.e
  pkgs.clang_12
		pkgs.ccls
		pkgs.gdb
		pkgs.gnumake
	];
}